version: '2.3'

volumes:
    grafana_data: {}
    loki_data: {}
    clickhouse_data: {}

services:
  grafana:
    image: grafana/grafana:master
    container_name: grafana
    volumes:
      - grafana_data:/var/lib/grafana
      - ./config/provisioning/:/etc/grafana/provisioning/
    environment:
      - GF_SECURITY_ADMIN_USER=${ADMIN_USER:-admin}
      - GF_SECURITY_ADMIN_PASSWORD=${ADMIN_PASSWORD:-admin}
      - GF_USERS_ALLOW_SIGN_UP=false
      - GF_EXPLORE_ENABLED=true
    restart: unless-stopped
    expose:
      - 3000

  minio:
    image: minio/minio
    container_name: minio
    volumes:
      - loki_data:/data
    ports:
      - "9001:9001"
    environment:
      MINIO_ACCESS_KEY: minio
      MINIO_SECRET_KEY: minio123
    command: server --address :9001 /data1-1
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9001/minio/health/live"]
      interval: 2s
      timeout: 5s
      retries: 60

  clickhouse-seed:
    image: yandex/clickhouse-server
    container_name: clickhouse-seed
    volumes:
      - clickhouse_data:/var/lib/clickhouse
      - "./config/storage.xml:/etc/clickhouse-server/config.d/storage.xml"
    ports:
      - 8123:8123
      - 9000:9000
      - 9009:9009
    depends_on:
      - minio
    healthcheck:
      test: clickhouse client --query='select 1'
      interval: 10s
      timeout: 10s
      retries: 10
      start_period: 300s
    cap_add:
      - SYS_PTRACE
    security_opt:
      - label:disable

  cloki:
    image: qxip/cloki:latest
    container_name: loki
    restart: unless-stopped
    ports:
      - "3100:3100"
    environment:
      - CLICKHOUSE_SERVER=clickhouse-seed
      - CLICKHOUSE_DB=cloki
      - CLICKHOUSE_AUTH="default:"
      - STORAGE_POLICY=external
      - DEBUG=false
    depends_on:
      - clickhouse-seed

  pastash:
    image: qxip/pastash-loki
    container_name: pastash
    volumes:
      - ./config/pastash.json:/config/loki.conf
      - /var/log:/var/log:ro
    depends_on:
      - cloki

