version: '2.3'

volumes:
  data1-1:
  clickhouse:

services:
  minio:
    extends:
      file: minio-service.yml
      service: minio

  minio-client:
    extends:
      file: minio-client.yml
      service: minio-client
    depends_on:
      minio:
        condition: service_healthy

  clickhouse1:
    extends:
      file: clickhouse-service.yml
      service: clickhouse
    user: clickhouse:clickhouse
    container_name: clickhouse1
    hostname: clickhouse1
    depends_on:
      minio-client:
        condition: service_healthy

  qryn:
    extends:
      file: qryn.yml
      service: qryn
    container_name: qryn
    depends_on:
      clickhouse1:
        condition: service_healthy

  pastash:
    extends:
      file: pastash.yml
      service: pastash
    container_name: pastash
    depends_on:
      clickhouse1:
        condition: service_healthy

  # dummy service which does nothing, but allows to postpone 
  # 'docker-compose up -d' till all dependecies will go healthy
  all_services_ready:
    image: hello-world
    depends_on:
      clickhouse1:
        condition: service_healthy
      minio:
        condition: service_healthy
