version: '2.3'

services:
  minio:
    image: minio/minio
    volumes:
      - data1-1:/data1
    ports:
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: minio123
    command: server --address :9001 /data1-1
    healthcheck:
      test: "timeout 5s bash -c ':> /dev/tcp/127.0.0.1/9000' || exit 1"
      interval: 5s
      retries: 1
      start_period: 5s
      timeout: 5s
