apiVersion: 1

datasources:
  - name: prometheus
    type: prometheus
    access: proxy
    url: http://qryn:3100
    isDefault: true
    user: test
    secureJsonData:
      password: test
    jsonData:
      prometheusType: Prometheus
    uid: "prometheus"
