{
 "title": "Telegraf Host Overview",
 "time": { "from": "2024-01-31T20:15:05.099Z", "to": "2024-01-31T20:17:01.585Z" },
 "templating": {
  "list": [
   {
    "name": "host",
    "query": {
     "query": "label_values(system_n_cpus, host)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Average CPU",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 7, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "avg_over_time({__name__=\"cpu_usage_guest\", cpu=\"cpu-total\", host=\"$host\"}[$__range])",
     "legendFormat": "cpu_usage_guest"
    },
    {
     "expr": "avg_over_time({__name__=\"cpu_usage_guest_nice\", cpu=\"cpu-total\", host=\"$host\"}[$__range])",
     "legendFormat": "cpu_usage_guest_nice"
    },
    {
     "expr": "avg_over_time({__name__=\"cpu_usage_iowait\", cpu=\"cpu-total\", host=\"$host\"}[$__range])",
     "legendFormat": "cpu_usage_iowait"
    },
    {
     "expr": "avg_over_time({__name__=\"cpu_usage_irq\", cpu=\"cpu-total\", host=\"$host\"}[$__range])\n",
     "legendFormat": "cpu_usage_irq"
    },
    {
     "expr": "avg_over_time({__name__=\"cpu_usage_nice\", cpu=\"cpu-total\", host=\"$host\"}[$__range])",
     "legendFormat": "cpu_usage_nice"
    },
    {
     "expr": "avg_over_time({__name__=\"cpu_usage_softirq\", cpu=\"cpu-total\", host=\"$host\"}[$__range])",
     "legendFormat": "cpu_usage_softirq"
    },
    {
     "expr": "avg_over_time({__name__=\"cpu_usage_steal\", cpu=\"cpu-total\", host=\"$host\"}[$__range])",
     "legendFormat": "cpu_usage_steal"
    },
    {
     "expr": "avg_over_time({__name__=\"cpu_usage_system\", cpu=\"cpu-total\", host=\"$host\"}[$__range])",
     "legendFormat": "cpu_usage_system"
    },
    {
     "expr": "avg_over_time({__name__=\"cpu_usage_user\", cpu=\"cpu-total\", host=\"$host\"}[$__range])",
     "legendFormat": "cpu_usage_user"
    }
   ]
  },
  {
   "title": "Average Memory Usage",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 7, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "avg_over_time(mem_used_percent{host=\"$host\"}[$__range])",
     "legendFormat": "{{__name__}}"
    }
   ]
  },
  {
   "title": "Average Swap Usage",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 3, "x": 11, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "avg_over_time(swap_used_percent{host=\"$host\"}[$__range])",
     "legendFormat": "{{__name__}}"
    }
   ]
  },
  {
   "title": "Average Disk Usage",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 6, "x": 14, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "avg_over_time(disk_used_percent{host=\"$host\"}[$__range])",
     "legendFormat": "{{__name__}} {{path}}"
    }
   ]
  },
  {
   "title": "Average Disk Inodes Usage",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 4, "x": 20, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "avg_over_time(disk_inodes_used{host=\"$host\"}[$__range]) / avg_over_time(disk_inodes_total{host=\"$host\"}[$__range]) * 100",
     "legendFormat": "{{device}} {{path}}"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "{__name__=~\"cpu_.*\", cpu=\"cpu-total\", host=\"$host\"}",
     "legendFormat": "{{__name__}}"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "{__name__=~\"(mem_|swap_)(used|total)\", host=\"$host\"}",
     "legendFormat": "{{__name__}}"
    }
   ]
  },
  {
   "title": "Network",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "rate(net_bytes_recv{host=\"$host\"}[10s])",
     "legendFormat": "net_bytes_recv {{interface}}"
    },
    {
     "expr": "- rate(net_bytes_sent{host=\"$host\"}[10s])",
     "legendFormat": "net_bytes_sent {{interface}}"
    }
   ]
  },
  {
   "title": "Processes Info",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "avg_over_time({__name__=~\"processes_blocked\", host=\"$host\"}[$__range])",
     "legendFormat": "processes_blocked"
    },
    {
     "expr": "avg_over_time({__name__=~\"processes_dead\", host=\"$host\"}[$__range])\n",
     "legendFormat": "processes_dead"
    },
    {
     "expr": "avg_over_time({__name__=~\"processes_idle\", host=\"$host\"}[$__range])",
     "legendFormat": "processes_idle"
    },
    {
     "expr": "avg_over_time({__name__=~\"processes_paging\", host=\"$host\"}[$__range])",
     "legendFormat": "processes_paging"
    },
    {
     "expr": "avg_over_time({__name__=~\"processes_running\", host=\"$host\"}[$__range])",
     "legendFormat": "processes_running"
    },
    {
     "expr": "avg_over_time({__name__=~\"processes_sleeping\", host=\"$host\"}[$__range])",
     "legendFormat": "processes_sleeping"
    },
    {
     "expr": "avg_over_time({__name__=~\"processes_stopped\", host=\"$host\"}[$__range])",
     "legendFormat": "processes_stopped"
    },
    {
     "expr": "avg_over_time({__name__=~\"processes_total\", host=\"$host\"}[$__range])",
     "legendFormat": "processes_total"
    },
    {
     "expr": "avg_over_time({__name__=~\"processes_total_threads\", host=\"$host\"}[$__range])",
     "legendFormat": "processes_total_threads"
    },
    {
     "expr": "avg_over_time({__name__=~\"processes_unknown\", host=\"$host\"}[$__range])",
     "legendFormat": "processes_unknown"
    },
    {
     "expr": "avg_over_time({__name__=~\"processes_zombies\", host=\"$host\"}[$__range])",
     "legendFormat": "processes_zombies"
    }
   ]
  },
  {
   "title": "System Load",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "{__name__=~\"system_load.*\", host=\"$host\"}",
     "legendFormat": "{{__name__}}"
    }
   ]
  },
  {
   "title": "Disk Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "{__name__=~\"disk_(used|total)\", host=\"$host\"}",
     "legendFormat": "{{__name__}}  {{path}}"
    }
   ]
  },
  {
   "title": "Docker Container CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum by (container_name)(docker_container_cpu_usage_percent{host=\"$host\"})",
     "legendFormat": "{{container_name}}"
    }
   ]
  },
  {
   "title": "Docker Container Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum by (container_name)(docker_container_mem_usage_percent{host=\"$host\"})",
     "legendFormat": "{{container_name}}"
    }
   ]
  },
  {
   "title": "Top 30 Processes Average CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 16, "w": 12, "x": 0, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "topk(30, procstat_cpu_usage{host=\"$host\"})",
     "legendFormat": "{{user}} {{pid}} {{process_name}} @ {{cmdline}}"
    }
   ]
  },
  {
   "title": "Top 30 Processes Average Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 16, "w": 12, "x": 12, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "topk(30, procstat_memory_usage{host=\"$host\"})",
     "legendFormat": "{{user}} {{pid}} {{process_name}} @ {{cmdline}}"
    }
   ]
  },
  {
   "title": "Processes Average CPU Usage",
   "type": "table",
   "gridPos": { "h": 15, "w": 12, "x": 0, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "procstat_cpu_usage{host=\"$host\"}",
     "legendFormat": "{{user}} {{pid}} {{process_name}} @ {{cmdline}}"
    }
   ]
  },
  {
   "title": "Processes Average Memory Usage",
   "type": "table",
   "gridPos": { "h": 15, "w": 12, "x": 12, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "procstat_memory_usage{host=\"$host\"}",
     "legendFormat": "{{user}} {{pid}} {{process_name}} @ {{cmdline}}"
    }
   ]
  }
 ]
}